name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository from github
      uses: actions/checkout@v3
    - name: build
      run: make
#   build-mac-os:
#     runs-on: macOS-latest
#     steps:
#     - name: Checkout repository from github
#       uses: actions/checkout@v3
#     - name: build
#       run: make
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository from github
      uses: actions/checkout@v3
    - name: build
      run: make
